/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#005236',
        'primary-fixed-dim': '#4edea3',
        background: '#faf8ff',
        surface: '#faf8ff',
        'on-tertiary-container': '#711419',
        'secondary-fixed-dim': '#9ed2b5',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#3c4a42',
        'surface-container-low': '#f2f3ff',
        'tertiary-container': '#fc7c78',
        'on-primary': '#ffffff',
        'surface-bright': '#faf8ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        outline: '#6c7a71',
        'on-tertiary-fixed': '#410005',
        'on-secondary-fixed': '#002113',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-variant': '#dae2fd',
        primary: '#006c49',
        'on-secondary-container': '#3c6c54',
        'secondary-container': '#b7ebce',
        'tertiary-fixed-dim': '#ffb3af',
        'on-primary-fixed': '#002113',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#1e4f3a',
        'outline-variant': '#bbcabf',
        'inverse-surface': '#283044',
        'on-surface': '#131b2e',
        tertiary: '#a43a3a',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eef0ff',
        'inverse-primary': '#4edea3',
        'on-primary-container': '#00422b',
        'primary-fixed': '#6ffbbe',
        secondary: '#376850',
        'on-tertiary-fixed-variant': '#842225',
        'primary-container': '#10b981',
        'on-background': '#131b2e',
        'tertiary-fixed': '#ffdad7',
        'surface-tint': '#006c49',
        'secondary-fixed': '#baeed1',
        'error-container': '#ffdad6',
        'surface-dim': '#d2d9f4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        glass: '0 18px 60px rgba(15, 23, 42, 0.12)',
      },
      backgroundImage: {
        'hero-fade':
          'linear-gradient(90deg, rgba(250,248,255,0.96) 0%, rgba(250,248,255,0.84) 42%, rgba(250,248,255,0) 100%)',
        'hero-fade-dark':
          'linear-gradient(90deg, rgba(2,6,23,0.94) 0%, rgba(2,6,23,0.72) 45%, rgba(2,6,23,0.08) 100%)',
      },
    },
  },
  plugins: [],
};
